apiVersion: v1
kind: Service
metadata:
  name: blackjack-server-service
spec:
  type: NodePort
  selector:
    app: blackjack-server
  ports:
  - name: "server-service"
    port: 5001
    targetPort: 3000
    nodePort: 31001
