apiVersion: v1
kind: Service
metadata:
  name: blackjack-ui-service
spec:
  type: NodePort
  selector:
    app: blackjack-ui
  ports:
  - name: "ui-service"
    port: 8080
    targetPort: 80
    nodePort: 31000
