name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server docker image
        run: |
          cd server
          docker build -t blackjack-buddy-server .

      - name: Build UI docker image
        run: |
          cd ui
          docker build -t blackjack-buddy-ui .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${{ github.workspace }}/kubeconfig.yml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: kubectl --kubeconfig ${{ github.workspace }}/kubeconfig.yml apply -f kubernetes/

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd test
          npm install

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test
